### ISSUE TITLE
Custom Problem

### ISSUE THREAD

**Issue by kavehsfv** [Codium-ai/AlphaCodium#14]
Is it possible to modify the code so that it works for a custom problem that is not included in the dataset?

**Comment by mrT23** [comment]
Anything is possible.

AlphaCodium is a flow that needs as input a problem, and public tests, in the format input-output.
see an example problem:
https://github.com/Codium-ai/AlphaCodium?tab=readme-ov-file#example-problem

The more your problem is "different" than CodeContest problems, the more adjustments you will probably need to make.

**Comment by kavehsfv** [comment]
Thank you for clarifying.
